#!/bin/sh

# Firefox settings
export MOZ_ACCELERATED=1
export MOZ_WEBRENDER=1

SCREEN_WIDTH=`xrandr 2>&1 | grep "Screen 0: minimum" | sed -e 's/.*, current //' -e 's/ x.*//'`
if [ "${SCREEN_WIDTH}" -ge 1920 ]; then
  echo "using HIDPI"
  export HIDPI=1
  # export GDK_SCALE=2
  export QT_SCALE_FACTOR=2
fi

if [ "$HIDPI" = "1" ]; then
  xrdb -DHIDPI=1 -DHOME=$HOME < ~/.Xresources
else
  xrdb -DHOME=$HOME < ~/.Xresources
fi

# Crazy fix for forward/back mouse buttons
# https://www.bsdhowto.ch/mousekeys.html
xmodmap -e "pointer = 1 2 3 8 9 10 11 4 5 6 7 12 13 14 15 16"

if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
  eval `dbus-launch --sh-syntax --exit-with-x11`
fi

setxkbmap -layout 'us' -option caps:swapescape
xsetroot -cursor_name left_ptr

autocutsel &

xidle &  # Config in .Xresources
xdotool behave_screen_edge --delay 2000 bottom-right exec xlock &

if ! ~/.fehbg 2> /dev/null; then
  xsetroot -solid steelblue
fi

if [ -f ~/.config/tint2/tint2rc ]; then
  tint2 &
fi

/usr/local/libexec/tray-app/sound &

~/.xsession.local

exec cwm
