#!/bin/sh

tailcolors() {
  ESC="$(printf '\033')"
  GREEN="${ESC}[32m"
  RED="${ESC}[31m"
  RESET="${ESC}[0m"

  if sed --version >/dev/null 2>&1; then
    sed -E \
      -e "s/\\<active\\>/${GREEN}active${RESET}/g" \
      -e "s/\\<relay\\>/${RED}relay${RESET}/g"
  else
    sed -E \
      -e "s/[[:<:]]active[[:>:]]/${GREEN}active${RESET}/g" \
      -e "s/[[:<:]]relay[[:>:]]/${RED}relay${RESET}/g"
  fi
}

if [ -f /Applications/Tailscale.app/Contents/MacOS/Tailscale ]; then
  tailscale=/Applications/Tailscale.app/Contents/MacOS/Tailscale
else
  tailscale=tailscale
fi

# shellcheck disable=SC2086
for host in $($tailscale status | awk '{print $2}'); do
  $tailscale ping --timeout=1s -c=5 $host > /dev/null 2>&1 &
done
wait

$tailscale status --active | tailcolors
